version: '3.1'

services:
  mariadb:
    image: mariadb
    env_file: ".env"
    ports:
      - "3306:3306"

  ems-api:
    build: ./ems-api/
    ports:
      - "5000:5000"
    volumes:
      ['./ems-api/:/app']
    env_file: "./ems-api/.env"

  ems-frontend:
    build: ./ems-frontend/
    container_name: ems-frontend-prod
    ports:
      - "8000:8000"
    env_file: "./ems-frontend/.env"
